version: "3.9"

services:
  server:
    env_file:
    - env/performance-level-1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - 8000:8000
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      source: .
      target: /www
    command:
    - python
    - server.py
